name: CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn test

  deploy:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy
        run: yarn deploy
