name: CD

on:
  push:
    branches:
      - main

env:
  REACT_APP_API_V1_BASE_URL: ${{secrets.REACT_APP_API_V1_BASE_URL}}

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'

  #     - name: Install Dependencies
  #       run: yarn install

  #     - name: Test
  #       run: yarn test

  deploy:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    # needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Deploy
        run: |
          git config --global user.email ${{ secrets.TALEL_GITHUB_EMAIL }}
          git config --global user.name "taleldayekh"
          git remote set-url origin https://${{ secrets.GHPAGES_DEPLOYMENT_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
