name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    name: Quality Assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn install

      - name: Static Code Analysis
        run: yarn lint

      - name: Test
        run: yarn test -- --coverage

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v1
